# Generated by Django 4.2.30 on 2026-04-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_audit_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("doc_type", models.CharField(max_length=4)),
                ("date_part", models.CharField(max_length=4)),
                ("last_seq", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_sequences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="documentsequence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "doc_type", "date_part"),
                name="uniq_doc_sequence_tenant_type_date",
            ),
        ),
        migrations.AddIndex(
            model_name="documentsequence",
            index=models.Index(fields=["tenant", "doc_type", "date_part"], name="common_docu_tenant__15ddbb_idx"),
        ),
    ]
