# Generated by Django 4.2.30 on 2026-04-19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowers", "0005_address_optional"),
        ("loans", "0002_loan_optional_fields_and_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("loan_due_alert", "Loan Due Alert")],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "borrower",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="borrowers.borrower",
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="loans.loan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "is_active", "is_read"], name="notificatio_user_id_6e07f5_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type", "due_date"], name="notificatio_type_f08f8a_idx"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=Q(("is_active", True)),
                fields=("user", "loan", "type", "due_date"),
                name="uniq_active_notification_user_loan_type_due",
            ),
        ),
    ]
