# Generated by Django 4.2.30 on 2026-04-20

from django.db import migrations, models
from django.db.models import Q


def backfill_notification_role_and_redirect(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    User = apps.get_model("users", "User")

    role_by_user_id = dict(User.objects.values_list("id", "role"))

    for notification in Notification.objects.all().iterator():
        role = role_by_user_id.get(notification.user_id, "admin")
        notification.role = role
        if not notification.redirect_target:
            notification.redirect_target = "/portal" if role == "borrower" else "/borrowers"
        notification.save(update_fields=["role", "redirect_target", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="external_key",
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="redirect_target",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="notification",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("collector", "Collector"),
                    ("borrower", "Borrower"),
                ],
                db_index=True,
                default="admin",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_notification_role_and_redirect, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("collection_task", "Collection Task"),
                    ("overdue_loan", "Overdue Loan"),
                    ("follow_up", "Follow Up"),
                    ("repayment_reminder", "Repayment Reminder"),
                    ("due_alert", "Due Alert"),
                    ("overdue_alert", "Overdue Alert"),
                    ("system_activity", "System Activity"),
                    ("escalation", "Escalation"),
                    ("system_update", "System Update"),
                    ("loan_due_alert", "Loan Due Alert"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="notificatio_type_f08f8a_idx",
        ),
        migrations.RemoveConstraint(
            model_name="notification",
            name="uniq_active_notification_user_loan_type_due",
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["type", "due_date", "role"], name="notif_type_due_role_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user", "created_at"], name="notif_user_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=Q(is_active=True, external_key__isnull=False),
                fields=("user", "external_key"),
                name="uniq_active_notification_user_external_key",
            ),
        ),
    ]
