# Generated by Django 4.2.30 on 2026-04-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections', to='loans.loan'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['date', 'status'], name='collections_date_dd455c_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['loan', 'date'], name='collections_loan_id_68a073_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['borrower', 'date'], name='collections_borrowe_4592e9_idx'),
        ),
    ]
