# Generated by Django 4.2.30 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0003_dailycollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="collection_code",
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
