# Generated by Django 4.2.30 on 2026-04-15 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_borrowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['mobile_number'], name='borrowers_b_mobile__7534cf_idx'),
        ),
        migrations.AddIndex(
            model_name='borrower',
            index=models.Index(fields=['status', 'updated_at'], name='borrowers_b_status_fd6bfa_idx'),
        ),
    ]
