# Generated by Django 4.2.30 on 2026-04-18 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrowers', '0003_borrower_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrower_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='guarantor_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='guarantor_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='id_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
