# Generated by Django 4.2.30 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrowers", "0004_borrower_user_alter_borrower_guarantor_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrower",
            name="address",
            field=models.TextField(blank=True, default=""),
        ),
    ]
