# Generated by Django 4.2.30 on 2026-04-18 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_status_b219e9_idx',
            old_name='accounts_ac_status_idx',
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_ac_borrowe_9b5ee0_idx',
            old_name='accounts_ac_borrower_idx',
        ),
    ]
