# Generated by Django 4.2.30 on 2026-05-02 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('hsn_code', models.CharField(blank=True, default='', max_length=10)),
                ('default_making_charge_formula', models.CharField(choices=[('PER_GRAM', 'Per Gram'), ('PCT_METAL', '% of Metal'), ('PER_PIECE', 'Per Piece')], default='PER_GRAM', max_length=20)),
                ('default_wastage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='jewellery.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('default_unit', models.CharField(default='gram', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='NumberSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('voucher_type', models.CharField(max_length=50)),
                ('prefix', models.CharField(max_length=20)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('padding', models.PositiveIntegerField(default=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['voucher_type'],
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('default_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('default_stones', models.JSONField(blank=True, default=dict)),
                ('default_labour', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('bom', models.JSONField(blank=True, default=dict)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designs', to='jewellery.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('rate_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_to', models.CharField(choices=[('JEWELLERY', 'Jewellery'), ('SERVICE', 'Service'), ('OTHER', 'Other')], default='JEWELLERY', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', 'name'],
                'indexes': [models.Index(fields=['tenant', 'applies_to', 'effective_from'], name='jewellery_t_tenant__e125e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Purity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=10)),
                ('pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purities', to='jewellery.metal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['metal__code', '-pct'],
                'indexes': [models.Index(fields=['tenant', 'metal', 'code'], name='jewellery_p_tenant__625f68_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='purity',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'metal', 'code'), name='uniq_jwl_purity_tenant_metal_code_active'),
        ),
        migrations.AddIndex(
            model_name='numberseries',
            index=models.Index(fields=['tenant', 'voucher_type'], name='jewellery_n_tenant__8d8c12_idx'),
        ),
        migrations.AddConstraint(
            model_name='numberseries',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'voucher_type'), name='uniq_jwl_series_tenant_voucher_type_active'),
        ),
        migrations.AddIndex(
            model_name='metal',
            index=models.Index(fields=['tenant', 'code'], name='jewellery_m_tenant__5fbd1d_idx'),
        ),
        migrations.AddConstraint(
            model_name='metal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code'), name='uniq_jwl_metal_tenant_code_active'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['tenant', 'category', 'code'], name='jewellery_d_tenant__007176_idx'),
        ),
        migrations.AddConstraint(
            model_name='design',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'code'), name='uniq_jwl_design_tenant_code_active'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tenant', 'parent', 'name'], name='jewellery_c_tenant__bb39ce_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'parent', 'name'), name='uniq_jwl_category_tenant_parent_name_active'),
        ),
    ]
