# Generated by Django 4.2.30 on 2026-04-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=150)),
                ('area_name', models.CharField(max_length=120)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('is_onboarded', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
