# Generated by Django 4.2.30 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="area_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
